### ISSUE TITLE
Wallet import export

### ISSUE THREAD

**Issue by Fonta1n3** [hodlwave/proof-wallet-v1#1]
Hey @hodlwave, it seems that Fully Noded and this project are a perfect match.

Would you be open to supporting this [wallet import export](https://github.com/Fonta1n3/FullyNoded/blob/master/Docs/Wallet-Export-Import.md) method?

It would make using a Proof-Wallet on FN incredibly easy and work with its psbt architecture nicely.

**Comment by hodlwave** [comment]
Picking up the discussion [here](https://github.com/hodlwave/proof-wallet/issues/2).
