### ISSUE TITLE
No module found `mnemonic`

### ISSUE THREAD

**Issue by Fonta1n3** [hodlwave/proof-wallet-v1#2]
Following the readme instructions on the other `proof-wallet` repo returns below error. Raising the issue here as it seems I can not raise an issue on the other repo.

```
Traceback (most recent call last):
  File "./glacierscript.py", line 39, in <module>
    from mnemonic import Mnemonic
ModuleNotFoundError: No module named 'mnemonic'
```

**Comment by Fonta1n3** [comment]
just needed to recurse submodules when cloning

**Comment by hodlwave** [comment]
sorry for the confusion :/
